version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres:9.6.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - /shared_folder/postgresql:/var/lib/postgresql
      - ./deploy/migration:/docker-entrypoint-initdb.d
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge